project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Chuqiao (Sebastian) Song"
  site-url: https://songcssebastian.github.io
  favicon: images/IMEG_1309.png
  repo-url: https://github.com/ss-sebastian/sebastian_song_personal_page.github.io
  repo-actions: [edit, issue]
  
  page-footer:
    left: |

    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#5249CC"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Food & Cooking"
        href: food.qmd
      - text: "Blogs"
        href: blog.qmd
      - text: "Codes"
        href: codes.qmd
      - text: "CV"
        href: CV_Chuqiao_SONG_Final.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细